# Data Cleaning

In [1]:
import os
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import requests
import time

pd.set_option('display.max_columns', None)

In [2]:
os.getcwd()

'C:\\Users\\lucas\\OneDrive\\Documenten\\HU\\HU_Jaar_4\\Minor_Big_Data_Design\\Sprint-2\\Hackaton'

In [3]:
# Load in the two data sets

dataset_pr = pd.read_csv(r"data/UGA_training_water_points.csv") # provided dataset
dataset_ext = pd.read_csv(r"data/Water_Point_Data_Exchange.csv") # external datasetda
data_testset = pd.read_csv(r"data/UGA_water_points_0y.csv")

C:\Users\lucas\AppData\Local\Temp\ipykernel_30296\897244848.py:4: DtypeWarning: Columns (14,15,17,18,19,22,23,25,26,27,30,40,41,58) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_ext = pd.read_csv(r"data/Water_Point_Data_Exchange.csv") # external datasetda
C:\Users\lucas\AppData\Local\Temp\ipykernel_30296\897244848.py:5: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  data_testset = pd.read_csv(r"data/UGA_water_points_0y.csv")

# Data exploration

In [4]:
dataset_pr.head()

,wpdx_id,status_id,water_tech_clean,water_source_clean,management_clean,unified_install_year,unified_installer,age_in_years,distance_to_primary,distance_to_secondary,distance_to_tertiary,distance_to_city,distance_to_town,is_urban,precipitation_5year,precipitation_10year,landcover_code,acled_index,isobioclimates,bgs_dtw,bgs_prod,bgs_stor,bgs_recharge,water_risk,rwi,assigned_population,local_population,usage_cap,pressure,criticality,population_1km,men_ratio_1km,women_of_reproductive_age_ratio_1km,youth_ratio_1km,elderly_ratio_1km,children_under_five_ratio_1km,population_10km,men_ratio_10km,women_of_reproductive_age_ratio_10km,youth_ratio_10km,elderly_ratio_10km,children_under_five_ratio_10km,population_100km,men_ratio_100km,women_of_reproductive_age_ratio_100km,youth_ratio_100km,elderly_ratio_100km,children_under_five_ratio_100km,orig_status_id,years_since_report,fold
0,6GGM73PJ+M94,Yes,NaN,Borehole,Community Management,2005.0,NaN,5.303326,36394.986551,8142.181088,9.467967,17705.931711,18451.607045,False,2195.944468,2219.945351,30,7.0,46,7.0,0.5,0.0,133.193283,2.085774,-0.402,35.0,463.0,300.0,0.116667,0.075594,2104.646729,0.485006,0.234015,0.206285,0.041460,0.176886,109028.375000,0.486389,0.233387,0.206274,0.041446,0.176912,11685379.0,0.482136,0.235319,0.206310,0.041488,0.176833,Yes,5.303326,2018-01-01
1,6GGJ7WGG+J24,Yes,NaN,Protected Spring,Community Management,2012.0,NaN,-1.692027,20943.627740,3687.605287,13.484889,23535.854658,10316.401780,False,2195.944468,2219.945351,10,1.0,46,0.0,0.5,0.0,133.193283,2.085774,0.286,355.0,750.0,250.0,1.420000,0.473333,1060.838989,0.501089,0.226707,0.206149,0.041298,0.177184,80276.992188,0.492128,0.230779,0.206225,0.041388,0.177018,11129700.0,0.482990,0.234932,0.206303,0.041480,0.176849,Yes,-1.692027,2018-01-01
2,6GGJ7WGG+J24,Yes,NaN,Protected Spring,Community Management,2012.0,NaN,0.607815,20943.627740,3687.605287,13.484889,23535.854658,10316.401780,False,2195.944468,2219.945351,10,1.0,46,0.0,0.5,0.0,133.193283,2.085774,0.286,355.0,750.0,250.0,1.420000,0.473333,1060.838989,0.501089,0.226707,0.206149,0.041298,0.177184,80276.992188,0.492128,0.230779,0.206225,0.041388,0.177018,11129700.0,0.482990,0.234932,0.206303,0.041480,0.176849,Yes,2.299842,2018-01-01
3,6GGM82GH+FQF,Yes,NaN,Protected Spring,Community Management,1991.0,NaN,19.332361,29766.833400,1983.752138,126.899244,17741.321230,11348.029995,False,2195.944468,2219.945351,10,6.0,46,0.0,0.5,0.0,133.193283,1.980204,-0.402,9.0,717.0,250.0,0.036000,0.012552,2633.038086,0.473817,0.239100,0.206380,0.041572,0.176678,114213.289062,0.491470,0.231078,0.206231,0.041395,0.177006,11378850.0,0.482567,0.235124,0.206306,0.041484,0.176841,Yes,19.332361,2018-01-01
4,6GGJ7X87+WF3,Yes,NaN,Borehole,Community Management,2006.0,NaN,4.328631,25127.842889,5492.323259,1300.493097,27541.568335,11631.402849,False,2195.944468,2219.945351,10,6.0,46,0.0,0.5,0.0,133.193283,2.085774,0.286,115.0,666.0,300.0,0.383333,0.172673,1423.184326,0.488072,0.232622,0.206259,0.041429,0.176943,84932.507812,0.492529,0.230597,0.206222,0.041384,0.177025,11378850.0,0.482567,0.235124,0.206306,0.041484,0.176841,Yes,4.328631,2018-01-01

In [5]:
dataset_pr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75203 entries, 0 to 75202
Data columns (total 51 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   wpdx_id                                75203 non-null  object
 1   status_id                              75203 non-null  object
 2   water_tech_clean                       0 non-null      float64
 3   water_source_clean                     75203 non-null  object
 4   management_clean                       71039 non-null  object
 5   unified_install_year                   74658 non-null  float64
 6   unified_installer                      4604 non-null   object
 7   age_in_years                           74658 non-null  float64
 8   distance_to_primary                    75203 non-null  float64
 9   distance_to_secondary                  75203 non-null  float64
 10  distance_to_tertiary                   75203 non-null  float64
 11  distance_to_city                       75203 non-null  float64
 12  distance_to_town                       75203 non-null  float64
 13  is_urban                               75203 non-null  bool
 14  precipitation_5year                    75203 non-null  float64
 15  precipitation_10year                   75203 non-null  float64
 16  landcover_code                         75203 non-null  int64
 17  acled_index                            75203 non-null  float64
 18  isobioclimates                         75203 non-null  int64
 19  bgs_dtw                                75203 non-null  float64
 20  bgs_prod                               75203 non-null  float64
 21  bgs_stor                               75203 non-null  float64
 22  bgs_recharge                           75203 non-null  float64
 23  water_risk                             75203 non-null  float64
 24  rwi                                    75203 non-null  float64
 25  assigned_population                    75144 non-null  float64
 26  local_population                       75144 non-null  float64
 27  usage_cap                              75186 non-null  float64
 28  pressure                               67226 non-null  float64
 29  criticality                            67226 non-null  float64
 30  population_1km                         75201 non-null  float64
 31  men_ratio_1km                          75201 non-null  float64
 32  women_of_reproductive_age_ratio_1km    75201 non-null  float64
 33  youth_ratio_1km                        75201 non-null  float64
 34  elderly_ratio_1km                      75201 non-null  float64
 35  children_under_five_ratio_1km          75201 non-null  float64
 36  population_10km                        75201 non-null  float64
 37  men_ratio_10km                         75201 non-null  float64
 38  women_of_reproductive_age_ratio_10km   75201 non-null  float64
 39  youth_ratio_10km                       75201 non-null  float64
 40  elderly_ratio_10km                     75201 non-null  float64
 41  children_under_five_ratio_10km         75201 non-null  float64
 42  population_100km                       75203 non-null  float64
 43  men_ratio_100km                        75203 non-null  float64
 44  women_of_reproductive_age_ratio_100km  75203 non-null  float64
 45  youth_ratio_100km                      75203 non-null  float64
 46  elderly_ratio_100km                    75203 non-null  float64
 47  children_under_five_ratio_100km        75203 non-null  float64
 48  orig_status_id                         75203 non-null  object
 49  years_since_report                     75203 non-null  float64
 50  fold                                   75203 non-null  object
dtypes: bool(1), float64(41), int64(2), object(7)
memory usage: 28.8+ MB

In [6]:
dataset_ext.head()

,row_id,#source,#lat_deg,#lon_deg,#report_date,#status_id,#water_source_clean,#water_source_category,#water_tech_clean,#water_tech_category,#facility_type,#clean_country_name,#clean_adm1,#clean_adm2,#clean_adm3,#clean_adm4,#install_year,#installer,#rehab_year,#rehabilitator,#management_clean,#status_clean,#pay,#fecal_coliform_presence,#fecal_coliform_value,#subjective_quality,#activity_id,#scheme_id,#wpdx_id,#notes,#orig_lnk,#photo_lnk,#country_id,#data_lnk,#distance_to_primary_road,#distance_to_secondary_road,#distance_to_tertiary_road,#distance_to_city,#distance_to_town,water_point_history,rehab_priority,water_point_population,local_population_1km,crucialness_score,pressure_score,usage_capacity,is_urban,days_since_report,staleness_score,latest_record,location_id,cluster_size,#clean_country_id,#country_name,#water_source,#water_tech,#status,#adm2,#adm3,#management,#adm1,New Georeferenced Column,lat_deg_original,lat_lon_deg,lon_deg_original,public_data_source,converted,count,created_timestamp,updated_timestamp
0,"651,816",Water For People,-15.726464,35.050673,06/11/2018 12:00:00 AM,Yes,NaN,NaN,Kiosk,Tapstand,Improved,Malawi,Blantyre,Blantyre City,n.a. (2465),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5GPQ73F2+C77,NaN,NaN,NaN,MW,https://catalog.waterpointdata.org/datasets/wf...,"7,034.825038384628","3,431.8103919239024",421.9067404563025,"8,321.854244069675","22,044.51487547918","{""2018-06-11"": {""source"": ""Water For People"", ...",NaN,NaN,NaN,NaN,NaN,250,True,"1,562",61.118046,True,"355,848",1,MWI,Malawi,NaN,Communal water kiosk,1,Kameza,NaN,NaN,Blantyre,POINT (35.0506729 -15.7264642),NaN,"(-15.7264642°, 35.0506729°)",NaN,https://catalog.waterpointdata.org/datafiles/w...,NaN,1,02/18/2022 05:36:33 AM,02/18/2022 05:36:33 AM
1,"584,864",Global Environment and Technology Foundation,6.723120,-1.581510,10/25/2017 12:00:00 AM,Yes,NaN,NaN,Tapstand,Tapstand,Improved,Ghana,Ashanti,Asokore Mampong Municipal,NaN,NaN,"2,017",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,6CRWPCF9+69X,NaN,NaN,NaN,GH,https://catalog.waterpointdata.org/datasets/wp...,"3,677.910097393717","3,944.7008064739625",690.130477381775,"5,362.010828423319","7,550.339233228932","{""2017-10-25"": {""source"": ""Global Environment ...",NaN,NaN,NaN,NaN,NaN,250,True,"1,791",56.861777,True,"349,148",1,GHA,Ghana,NaN,Standpost,NaN,NaN,NaN,NaN,NaN,POINT (-1.58151 6.72312),NaN,"(6.72312°, -1.58151°)",NaN,https://catalog.waterpointdata.org/datafiles/w...,NaN,1,07/29/2020 07:21:47 PM,07/29/2020 07:21:47 PM
2,"509,399",GOAL,8.001933,-11.287600,12/31/2010 12:00:00 AM,Yes,NaN,NaN,Tapstand,Tapstand,Improved,Sierra Leone,Eastern,Kenema,Kando Leppeama,NaN,NaN,Water Aid,NaN,NaN,NaN,Functional,NaN,NaN,NaN,NaN,NaN,NaN,6CWC2P26+QXC,Poor…Jenneh…Kandu Leppiema……,NaN,NaN,SL,https://catalog.waterpointdata.org/datasets/go...,"17,540.362241781073","4,052.9332940172294",104.43156160925501,"17,003.136159836264","15,474.442790152856","{""2010-12-31"": {""source"": ""GOAL"", ""status_id"":...",NaN,NaN,NaN,NaN,NaN,250,False,"4,281",25.938867,True,"98,255",1,SLE,Sierra Leone,Gravity stand-post,NaN,Functional,Kenema,NaN,NaN,Eastern,POINT (-11.2876 8.00193333333),NaN,"(8.00193333333°, -11.2876°)",NaN,https://catalog.waterpointdata.org/datafiles/g...,"#install_year, #notes",1,07/30/2020 08:35:45 AM,07/30/2020 08:35:45 AM
3,"21,983",WASH Liberia,8.084948,-10.125945,12/04/2015 12:00:00 AM,Yes,NaN,NaN,Tapstand,Tapstand,Improved,Liberia,Lofa,Kolahun,Lucasu,NaN,NaN,NaN,NaN,NaN,School Management,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6CWF3VMF+XJF,NaN,https://wash-liberia.org/raw-water-point-data/,NaN,LR,https://catalog.waterpointdata.org/datasets/wa...,"21,602.13764050712","37,030.19501334659","14,456.723950112362","52,727.38905586436","31,606.464896789807","{""2015-12-04"": {""source"": ""WASH Liberia"", ""sta...",NaN,NaN,NaN,NaN,NaN,250,False,"2,482",45.732584,True,"285,679",1,LBR,Liberia,Public standpipe,NaN,NaN,NaN,NaN,Institutional Management - School,Lofa,POINT (-10.12594524 8.08494814),NaN,"(8.08494814°, -10.12594524°)",NaN,https://catalog.waterpointdata.org/datafiles/w...,#status,1,09/11/2020 11:22:31 AM,09/11/2020 11:22:31 AM
4,"660,321",Water For People,0.186855,30.446588,03/14/2019 12:00:00 AM,Yes,Piped Water,Piped Water,NaN,NaN,Improved,Uganda,Western,Kamwenge,Kibale,Kamwenge Town Council,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Present,NaN,NaN,NaN,NaN,6GGG5CPW+PJW,NaN,NaN,NaN,UG,https://catalog.waterpointdata.org/datasets/wf...,"31,948.122428728428",593.6958182047109,149.01742389861994,"40,206.410975449166","35,770.43571525792","{""2019-03-14"": {""source"": ""Water For People"", ...",NaN,NaN,NaN,NaN,NaN,250,False,"1,286",66.673396,True,"362,508",1,UGA,Uganda,NaN,Pumped piped system,1,Kibale,Kamwenge T/Council,NaN,Kamwenge,POINT (30.44658833 0.186855),NaN,"(0.186855°, 30.44658833°)",NaN,https://catalog.waterpointdata.org/datafiles/w...,NaN,1,02/18/2022 05:36:33 AM,02/18/2022 05:36:33 AM

In [7]:
dataset_ext.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406566 entries, 0 to 406565
Data columns (total 70 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   row_id                       406566 non-null  object
 1   #source                      406566 non-null  object
 2   #lat_deg                     406566 non-null  float64
 3   #lon_deg                     406566 non-null  float64
 4   #report_date                 406566 non-null  object
 5   #status_id                   406566 non-null  object
 6   #water_source_clean          377396 non-null  object
 7   #water_source_category       377396 non-null  object
 8   #water_tech_clean            285742 non-null  object
 9   #water_tech_category         285742 non-null  object
 10  #facility_type               406566 non-null  object
 11  #clean_country_name          406566 non-null  object
 12  #clean_adm1                  406566 non-null  object
 13  #clean_adm2                  406566 non-null  object
 14  #clean_adm3                  267531 non-null  object
 15  #clean_adm4                  122488 non-null  object
 16  #install_year                273679 non-null  object
 17  #installer                   93063 non-null   object
 18  #rehab_year                  130 non-null     object
 19  #rehabilitator               253 non-null     object
 20  #management_clean            273845 non-null  object
 21  #status_clean                300865 non-null  object
 22  #pay                         221005 non-null  object
 23  #fecal_coliform_presence     6068 non-null    object
 24  #fecal_coliform_value        3818 non-null    float64
 25  #subjective_quality          166579 non-null  object
 26  #activity_id                 197374 non-null  object
 27  #scheme_id                   20127 non-null   object
 28  #wpdx_id                     406566 non-null  object
 29  #notes                       220189 non-null  object
 30  #orig_lnk                    94045 non-null   object
 31  #photo_lnk                   176191 non-null  object
 32  #country_id                  405755 non-null  object
 33  #data_lnk                    406566 non-null  object
 34  #distance_to_primary_road    406566 non-null  object
 35  #distance_to_secondary_road  406566 non-null  object
 36  #distance_to_tertiary_road   406566 non-null  object
 37  #distance_to_city            406428 non-null  object
 38  #distance_to_town            406566 non-null  object
 39  water_point_history          406566 non-null  object
 40  rehab_priority               103172 non-null  object
 41  water_point_population       365825 non-null  object
 42  local_population_1km         365825 non-null  object
 43  crucialness_score            291244 non-null  float64
 44  pressure_score               291149 non-null  float64
 45  usage_capacity               406382 non-null  object
 46  is_urban                     406566 non-null  bool
 47  days_since_report            406566 non-null  object
 48  staleness_score              406566 non-null  float64
 49  latest_record                406566 non-null  bool
 50  location_id                  406566 non-null  object
 51  cluster_size                 406566 non-null  int64
 52  #clean_country_id            406566 non-null  object
 53  #country_name                405755 non-null  object
 54  #water_source                389101 non-null  object
 55  #water_tech                  262555 non-null  object
 56  #status                      314290 non-null  object
 57  #adm2                        364926 non-null  object
 58  #adm3                        27954 non-null   object
 59  #management                  274655 non-null  object
 60  #adm1                        376108 non-null  object
 61  New Georeferenced Column     406566 non-null  object
 62  lat_deg_original             42881 non-null   float64
 63  lat_lon_deg                  406566 non-null  object
 64  lon_deg_original             42881 non-null   float64
 65  public_data_source           406566 non-null  object
 66  converted                    342028 non-null  object
 67  count                        406566 non-null  int64
 68  created_timestamp            406566 non-null  object
 69  updated_timestamp            406566 non-null  object
dtypes: bool(2), float64(8), int64(2), object(58)
memory usage: 211.7+ MB

The external dataset includes a lot of african countries. We only want to keep the data for the country Uganda.

In [8]:
dataset_ext['#country_name'].head()

0          Malawi
1           Ghana
2    Sierra Leone
3         Liberia
4          Uganda
Name: #country_name, dtype: object

In [9]:
# make dataset with Uganda data
dataset_uganda = dataset_ext.loc[dataset_ext['#country_name'] == "Uganda"]

We discussed which columns of this external dataset we wanted to keep initially

In [10]:
dataset_uganda = dataset_uganda[['#wpdx_id', '#source', '#lat_deg', '#lon_deg', '#clean_adm1', '#clean_adm2', 'days_since_report', 'staleness_score', 'cluster_size']]

In [11]:
dataset_uganda.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95878 entries, 4 to 385426
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   #wpdx_id           95878 non-null  object
 1   #source            95878 non-null  object
 2   #lat_deg           95878 non-null  float64
 3   #lon_deg           95878 non-null  float64
 4   #clean_adm1        95878 non-null  object
 5   #clean_adm2        95878 non-null  object
 6   days_since_report  95878 non-null  object
 7   staleness_score    95878 non-null  float64
 8   cluster_size       95878 non-null  int64
dtypes: float64(3), int64(1), object(5)
memory usage: 7.3+ MB

In [12]:
# both dataset have the same ideentifiers, but we need to make sure the cilumn names are the same
dataset_pr = dataset_pr.rename(columns={'wpdx_id': '#wpdx_id'})

In [13]:
datasets_combined = dataset_pr.merge(dataset_uganda, on = '#wpdx_id')
datasets_combined = datasets_combined.drop(columns=['water_tech_clean', 'unified_installer' ])

In [14]:
datasets_combined.head()

,#wpdx_id,status_id,water_source_clean,management_clean,unified_install_year,age_in_years,distance_to_primary,distance_to_secondary,distance_to_tertiary,distance_to_city,distance_to_town,is_urban,precipitation_5year,precipitation_10year,landcover_code,acled_index,isobioclimates,bgs_dtw,bgs_prod,bgs_stor,bgs_recharge,water_risk,rwi,assigned_population,local_population,usage_cap,pressure,criticality,population_1km,men_ratio_1km,women_of_reproductive_age_ratio_1km,youth_ratio_1km,elderly_ratio_1km,children_under_five_ratio_1km,population_10km,men_ratio_10km,women_of_reproductive_age_ratio_10km,youth_ratio_10km,elderly_ratio_10km,children_under_five_ratio_10km,population_100km,men_ratio_100km,women_of_reproductive_age_ratio_100km,youth_ratio_100km,elderly_ratio_100km,children_under_five_ratio_100km,orig_status_id,years_since_report,fold,#source,#lat_deg,#lon_deg,#clean_adm1,#clean_adm2,days_since_report,staleness_score,cluster_size
0,6GGM73PJ+M94,Yes,Borehole,Community Management,2005.0,5.303326,36394.986551,8142.181088,9.467967,17705.931711,18451.607045,False,2195.944468,2219.945351,30,7.0,46,7.0,0.5,0.0,133.193283,2.085774,-0.402,35.0,463.0,300.0,0.116667,0.075594,2104.646729,0.485006,0.234015,0.206285,0.041460,0.176886,109028.375000,0.486389,0.233387,0.206274,0.041446,0.176912,11685379.0,0.482136,0.235319,0.206310,0.041488,0.176833,Yes,5.303326,2018-01-01,"Ministry of Water and Environment, Uganda",0.286628,33.080945,Central,Buikwe,"4,534",23.950605,1
1,6GGJ7WGG+J24,Yes,Protected Spring,Community Management,2012.0,-1.692027,20943.627740,3687.605287,13.484889,23535.854658,10316.401780,False,2195.944468,2219.945351,10,1.0,46,0.0,0.5,0.0,133.193283,2.085774,0.286,355.0,750.0,250.0,1.420000,0.473333,1060.838989,0.501089,0.226707,0.206149,0.041298,0.177184,80276.992188,0.492128,0.230779,0.206225,0.041388,0.177018,11129700.0,0.482990,0.234932,0.206303,0.041480,0.176849,Yes,-1.692027,2018-01-01,"Ministry of Water and Environment, Uganda",0.276332,32.925220,Central,Buikwe,"3,693",31.220904,2
2,6GGJ7WGG+J24,Yes,Protected Spring,Community Management,2012.0,0.607815,20943.627740,3687.605287,13.484889,23535.854658,10316.401780,False,2195.944468,2219.945351,10,1.0,46,0.0,0.5,0.0,133.193283,2.085774,0.286,355.0,750.0,250.0,1.420000,0.473333,1060.838989,0.501089,0.226707,0.206149,0.041298,0.177184,80276.992188,0.492128,0.230779,0.206225,0.041388,0.177018,11129700.0,0.482990,0.234932,0.206303,0.041480,0.176849,Yes,2.299842,2018-01-01,"Ministry of Water and Environment, Uganda",0.276332,32.925220,Central,Buikwe,"3,693",31.220904,2
3,6GGM82GH+FQF,Yes,Protected Spring,Community Management,1991.0,19.332361,29766.833400,1983.752138,126.899244,17741.321230,11348.029995,False,2195.944468,2219.945351,10,6.0,46,0.0,0.5,0.0,133.193283,1.980204,-0.402,9.0,717.0,250.0,0.036000,0.012552,2633.038086,0.473817,0.239100,0.206380,0.041572,0.176678,114213.289062,0.491470,0.231078,0.206231,0.041395,0.177006,11378850.0,0.482567,0.235124,0.206306,0.041484,0.176841,Yes,19.332361,2018-01-01,"Ministry of Water and Environment, Uganda",0.326192,33.029432,Central,Buikwe,"4,524",24.026219,1
4,6GGJ7X87+WF3,Yes,Borehole,Community Management,2006.0,4.328631,25127.842889,5492.323259,1300.493097,27541.568335,11631.402849,False,2195.944468,2219.945351,10,6.0,46,0.0,0.5,0.0,133.193283,2.085774,0.286,115.0,666.0,300.0,0.383333,0.172673,1423.184326,0.488072,0.232622,0.206259,0.041429,0.176943,84932.507812,0.492529,0.230597,0.206222,0.041384,0.177025,11378850.0,0.482567,0.235124,0.206306,0.041484,0.176841,Yes,4.328631,2018-01-01,"Ministry of Water and Environment, Uganda",0.267267,32.963657,Central,Buikwe,"4,525",24.018647,1

In [15]:
datasets_combined['#clean_adm1'].value_counts()

Western     24745
Northern    19895
Eastern     16476
Central     13185
Name: #clean_adm1, dtype: int64

In [16]:
datasets_combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74301 entries, 0 to 74300
Data columns (total 57 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   #wpdx_id                               74301 non-null  object
 1   status_id                              74301 non-null  object
 2   water_source_clean                     74301 non-null  object
 3   management_clean                       70609 non-null  object
 4   unified_install_year                   73756 non-null  float64
 5   age_in_years                           73756 non-null  float64
 6   distance_to_primary                    74301 non-null  float64
 7   distance_to_secondary                  74301 non-null  float64
 8   distance_to_tertiary                   74301 non-null  float64
 9   distance_to_city                       74301 non-null  float64
 10  distance_to_town                       74301 non-null  float64
 11  is_urban                               74301 non-null  bool
 12  precipitation_5year                    74301 non-null  float64
 13  precipitation_10year                   74301 non-null  float64
 14  landcover_code                         74301 non-null  int64
 15  acled_index                            74301 non-null  float64
 16  isobioclimates                         74301 non-null  int64
 17  bgs_dtw                                74301 non-null  float64
 18  bgs_prod                               74301 non-null  float64
 19  bgs_stor                               74301 non-null  float64
 20  bgs_recharge                           74301 non-null  float64
 21  water_risk                             74301 non-null  float64
 22  rwi                                    74301 non-null  float64
 23  assigned_population                    74243 non-null  float64
 24  local_population                       74243 non-null  float64
 25  usage_cap                              74285 non-null  float64
 26  pressure                               66367 non-null  float64
 27  criticality                            66367 non-null  float64
 28  population_1km                         74299 non-null  float64
 29  men_ratio_1km                          74299 non-null  float64
 30  women_of_reproductive_age_ratio_1km    74299 non-null  float64
 31  youth_ratio_1km                        74299 non-null  float64
 32  elderly_ratio_1km                      74299 non-null  float64
 33  children_under_five_ratio_1km          74299 non-null  float64
 34  population_10km                        74299 non-null  float64
 35  men_ratio_10km                         74299 non-null  float64
 36  women_of_reproductive_age_ratio_10km   74299 non-null  float64
 37  youth_ratio_10km                       74299 non-null  float64
 38  elderly_ratio_10km                     74299 non-null  float64
 39  children_under_five_ratio_10km         74299 non-null  float64
 40  population_100km                       74301 non-null  float64
 41  men_ratio_100km                        74301 non-null  float64
 42  women_of_reproductive_age_ratio_100km  74301 non-null  float64
 43  youth_ratio_100km                      74301 non-null  float64
 44  elderly_ratio_100km                    74301 non-null  float64
 45  children_under_five_ratio_100km        74301 non-null  float64
 46  orig_status_id                         74301 non-null  object
 47  years_since_report                     74301 non-null  float64
 48  fold                                   74301 non-null  object
 49  #source                                74301 non-null  object
 50  #lat_deg                               74301 non-null  float64
 51  #lon_deg                               74301 non-null  float64
 52  #clean_adm1                            74301 non-null  object
 53  #clean_adm2                            74301 non-null  object
 54  days_since_report                      74301 non-null  object
 55  staleness_score                        74301 non-null  float64
 56  cluster_size                           74301 non-null  int64
dtypes: bool(1), float64(43), int64(3), object(10)
memory usage: 32.4+ MB

## Clean testset

In [54]:
data_testset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80202 entries, 0 to 80201
Data columns (total 56 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   wpdx_id                                80202 non-null  object
 1   clean_country_id                       80202 non-null  object
 2   clean_adm1                             80202 non-null  object
 3   clean_adm2                             80202 non-null  object
 4   lat_deg                                80202 non-null  float64
 5   lon_deg                                80202 non-null  float64
 6   water_tech_clean                       2 non-null      object
 7   water_source_clean                     80202 non-null  object
 8   management_clean                       70406 non-null  object
 9   unified_install_year                   68577 non-null  float64
 10  unified_installer                      3635 non-null   object
 11  age_in_years                           68577 non-null  float64
 12  distance_to_primary                    80202 non-null  float64
 13  distance_to_secondary                  80202 non-null  float64
 14  distance_to_tertiary                   80202 non-null  float64
 15  distance_to_city                       80202 non-null  float64
 16  distance_to_town                       80202 non-null  float64
 17  is_urban                               80202 non-null  bool
 18  precipitation_5year                    80202 non-null  float64
 19  precipitation_10year                   80202 non-null  float64
 20  landcover_code                         80202 non-null  int64
 21  acled_index                            80202 non-null  float64
 22  isobioclimates                         80202 non-null  int64
 23  bgs_dtw                                80202 non-null  float64
 24  bgs_prod                               80202 non-null  float64
 25  bgs_stor                               80202 non-null  float64
 26  bgs_recharge                           80202 non-null  float64
 27  water_risk                             80202 non-null  float64
 28  rwi                                    80202 non-null  float64
 29  assigned_population                    79934 non-null  float64
 30  local_population                       79934 non-null  float64
 31  usage_cap                              80162 non-null  float64
 32  pressure                               70898 non-null  float64
 33  criticality                            70899 non-null  float64
 34  population_1km                         80200 non-null  float64
 35  men_ratio_1km                          80200 non-null  float64
 36  women_of_reproductive_age_ratio_1km    80200 non-null  float64
 37  youth_ratio_1km                        80200 non-null  float64
 38  elderly_ratio_1km                      80200 non-null  float64
 39  children_under_five_ratio_1km          80200 non-null  float64
 40  population_10km                        80200 non-null  float64
 41  men_ratio_10km                         80200 non-null  float64
 42  women_of_reproductive_age_ratio_10km   80200 non-null  float64
 43  youth_ratio_10km                       80200 non-null  float64
 44  elderly_ratio_10km                     80200 non-null  float64
 45  children_under_five_ratio_10km         80200 non-null  float64
 46  population_100km                       80202 non-null  float64
 47  men_ratio_100km                        80202 non-null  float64
 48  women_of_reproductive_age_ratio_100km  80202 non-null  float64
 49  youth_ratio_100km                      80202 non-null  float64
 50  elderly_ratio_100km                    80202 non-null  float64
 51  children_under_five_ratio_100km        80202 non-null  float64
 52  history                                80202 non-null  object
 53  fold                                   0 non-null      float64
 54  years_since_report                     80202 non-null  float64
 55  orig_status_id                         80202 non-null  object
dtypes: bool(1), float64(43), int64(2), object(10)
memory usage: 33.7+ MB

In [78]:
data_testset.head()

,wpdx_id,clean_country_id,clean_adm1,clean_adm2,lat_deg,lon_deg,water_tech_clean,water_source_clean,management_clean,unified_install_year,unified_installer,age_in_years,distance_to_primary,distance_to_secondary,distance_to_tertiary,distance_to_city,distance_to_town,is_urban,precipitation_5year,precipitation_10year,landcover_code,acled_index,isobioclimates,bgs_dtw,bgs_prod,bgs_stor,bgs_recharge,water_risk,rwi,assigned_population,local_population,usage_cap,pressure,criticality,population_1km,men_ratio_1km,women_of_reproductive_age_ratio_1km,youth_ratio_1km,elderly_ratio_1km,children_under_five_ratio_1km,population_10km,men_ratio_10km,women_of_reproductive_age_ratio_10km,youth_ratio_10km,elderly_ratio_10km,children_under_five_ratio_10km,population_100km,men_ratio_100km,women_of_reproductive_age_ratio_100km,youth_ratio_100km,elderly_ratio_100km,children_under_five_ratio_100km,history,fold,years_since_report,orig_status_id
0,6GFGW93X+XFX,UGA,Western,Kitagwenda,-0.095018,30.398732,NaN,Piped Water,NaN,NaN,NaN,NaN,35495.540846,50.465283,143.858262,45701.058741,11575.940724,False,732.824643,743.928750,10,0.0,46,0.0,0.5,0.0,67.648903,2.084471,-0.388,NaN,NaN,250.0,NaN,NaN,1855.527710,0.484433,0.234276,0.206290,0.041465,0.176875,102586.765625,0.481990,0.235386,0.206311,0.041490,0.176830,5797803.5,0.486992,0.233093,0.206153,0.041491,0.176957,"{""2019-03-22"": {""source"": ""Water For People"", ...",NaN,3.685223,Yes
1,6GFGW83H+7HH,UGA,Western,Kitagwenda,-0.096813,30.328976,NaN,Piped Water,NaN,1962.0,NaN,60.904741,28339.551870,6726.377522,189.561421,40242.518250,18981.997688,False,660.009782,657.486121,10,1.0,46,0.0,0.5,0.0,69.435242,2.084471,-0.388,NaN,NaN,250.0,NaN,NaN,1328.025879,0.479946,0.236315,0.206328,0.041510,0.176792,101707.296875,0.486392,0.233386,0.206274,0.041446,0.176912,5624771.5,0.486366,0.233369,0.206115,0.041516,0.176958,"{""2014-03-26"": {""photo_lnk"": ""https://akvoflow...",NaN,8.673689,Yes
2,6GGG9R38+868,UGA,Western,Kamwenge,0.353288,30.815570,NaN,Piped Water,NaN,NaN,NaN,NaN,22490.392840,23843.167254,8.053570,68581.935092,30203.607039,False,1145.257513,1127.345324,10,0.0,46,0.0,0.1,0.0,67.575142,2.085774,-0.229,NaN,NaN,250.0,NaN,NaN,1252.549194,0.494763,0.229582,0.206202,0.041362,0.177067,87837.289062,0.491424,0.231099,0.206231,0.041395,0.177005,5860948.5,0.493494,0.230157,0.206202,0.041380,0.177047,"{""2021-03-31"": {""source"": ""Water For People"", ...",NaN,1.659172,Yes
3,6GFGW7W5+93V,UGA,Western,Kitagwenda,-0.054041,30.257572,NaN,Piped Water,Private Operator/Delegated Management,2000.0,NaN,22.905330,23496.276320,12027.104796,255.647062,31510.597883,18645.740632,False,660.009782,657.486121,190,1.0,35,7.0,1.0,10000.0,66.518852,2.084471,-0.206,NaN,NaN,250.0,NaN,NaN,2329.741943,0.497711,0.228242,0.206178,0.041332,0.177121,57439.492188,0.492778,0.230484,0.206219,0.041382,0.177030,5624771.5,0.486366,0.233369,0.206115,0.041516,0.176958,"{""2014-03-26"": {""photo_lnk"": ""https://akvoflow...",NaN,6.721562,Yes
4,6GGG8CGW+6W6,UGA,Western,Kamwenge,0.325527,30.447257,NaN,Piped Water,NaN,NaN,NaN,NaN,26383.753885,52.823791,1001.701787,41134.803447,38410.828795,False,903.322577,905.025323,10,0.0,46,0.0,0.5,0.0,66.306778,2.084471,-0.534,NaN,NaN,250.0,NaN,NaN,1390.329834,0.481046,0.235815,0.206319,0.041499,0.176812,62092.359375,0.480734,0.235957,0.206322,0.041502,0.176807,5564531.0,0.490159,0.231638,0.206039,0.041498,0.177041,"{""2019-03-15"": {""source"": ""Water For People"", ...",NaN,3.704388,Yes

In [55]:
data_testset['clean_country_id'].value_counts()

UGA    80202
Name: clean_country_id, dtype: int64

All data in de test set is from Uganda, and the dataset has coordinates so we won't have to merge or slice this dataset

# Add new data points (elevation in m) to database
We decided to use existing data (coordinates) to make new dat points (Elevation in m) so we can use it in our prediction model

In [29]:
# source: https://stackoverflow.com/a/51064850/18261474

# script for returning elevation from lat, long, based on open elevation data
# which in turn is based on SRTM
def get_elevation(lat, long):
    time.sleep(0.05) # added a sleep timer because we would overload the api otherwise
    query = ('https://api.open-elevation.com/api/v1/lookup'
             f'?locations={lat},{long}')
    r = requests.get(query).json()  # json object, various ways you can extract value
    # one approach is to use pandas json functionality:
    elevation = pd.json_normalize(r, 'results')['elevation'].values[0]
    return elevation

In [30]:
# test fucntion
get_elevation(0.316231, 32.966182)

1253

Now we can add a column with the elevation data to each row with the code below

**Note:** due to errors of making too many requests to the API and resulting in errors when its maybe 3/4 done, we split the database up in smaller parts to make some sort of "Checkpoints". Its doesnt look pretty but this quick fix is needed.

In [31]:
df_split = np.array_split(datasets_combined, 12)

In [32]:
df1 = df_split[0]
df1['altitude`_in_m'] = df1.apply(lambda row: get_elevation(row['lat_deg'], row['#lon_deg']), axis=1)

In [33]:
df2 = df_split[1]
df2['altitude`_in_m'] = df2.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [34]:
df3 = df_split[2]
df3['altitude`_in_m'] = df3.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [35]:
df4 = df_split[3]
df4['altitude`_in_m'] = df4.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [36]:
df5 = df_split[4]
df5['altitude`_in_m'] = df5.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [37]:
df6 = df_split[5]
df6['altitude`_in_m'] = df6.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [38]:
df7 = df_split[6]
df7['altitude`_in_m'] = df7.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [39]:
df8 = df_split[7]
df8['altitude`_in_m'] = df8.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [40]:
df9 = df_split[8]
df9['altitude`_in_m'] = df9.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [41]:
df10 = df_split[9]
df10['altitude`_in_m'] = df10.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [42]:
df11 = df_split[10]
df11['altitude`_in_m'] = df11.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [44]:
df12 = df_split[11]
df12['altitude`_in_m'] = df12.apply(lambda row: get_elevation(row['#lat_deg'], row['#lon_deg']), axis=1)

In [48]:
dataset_with_elevation = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], axis=0, ignore_index=True)

In [50]:
dataset_with_elevation.to_pickle('dataset_elevation.pkl')

### Now we add elevation data to the test set `data_testset`

In [51]:
df_split_ts = np.array_split(data_testset, 15)

In [58]:
df1_ts = df_split_ts[0]
df1_ts['altitude`_in_m'] = df1_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [59]:
df2_ts = df_split_ts[1]
df2_ts['altitude`_in_m'] = df2_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [60]:
df3_ts = df_split_ts[2]
df3_ts['altitude`_in_m'] = df3_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [61]:
df4_ts = df_split_ts[3]
df4_ts['altitude`_in_m'] = df4_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [63]:
df5_ts = df_split_ts[4]
df5_ts['altitude`_in_m'] = df5_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [64]:
df6_ts = df_split_ts[5]
df6_ts['altitude`_in_m'] = df6_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [67]:
df7_ts = df_split_ts[6]
df7_ts['altitude`_in_m'] = df7_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [136]:
df8_ts = df_split_ts[7]
df8_ts['altitude`_in_m'] = df8_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [137]:
df9_ts = df_split_ts[8]
df9_ts['altitude`_in_m'] = df9_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [138]:
df10_ts = df_split_ts[9]
df10_ts['altitude`_in_m'] = df10_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [139]:
df11_ts = df_split_ts[10]
df11_ts['altitude`_in_m'] = df11_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [140]:
df12_ts = df_split_ts[11]
df12_ts['altitude`_in_m'] = df12_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [141]:
df13_ts = df_split_ts[12]
df13_ts['altitude`_in_m'] = df13_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [142]:
df14_ts = df_split_ts[13]
df14_ts['altitude`_in_m'] = df14_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

In [144]:
df15_ts = df_split_ts[14]
df15_ts['altitude`_in_m'] = df15_ts.apply(lambda row: get_elevation(row['lat_deg'], row['lon_deg']), axis=1)

IndexError: list index out of range

In [151]:
testset_with_elevation = pd.concat([df1_ts, df2_ts, df3_ts, df4_ts, df5_ts, df6_ts,
                                    df7_ts, df8_ts, df9_ts, df10_ts, df11_ts, df12_ts,
                                    df13_ts, df14_ts], axis=0, ignore_index=True)

In [152]:
testset_with_elevation.to_pickle('testset_elevation.pkl')

# Data cleaning

TO-DO: `bgs_recharge` from float to int

### chosen features

- `water_source_clean`: Cleaned version of the water source data.
- `management_clean `: Select the classification of the entity that directly manages the water point.
- `age_in_years`: 
- `distance_to_primary`: Distance between water point and nearest primary road per OpenStreetMap
- `distance_to_city`: Distance between water point and nearest city per OpenStreetMap
- `distance_to_town`: Distance between water point and nearest town per OpenStreetMap
- `landcover_code`: Extraction of point values for landcover at each water point GPS location from 2020 dataset.
- `acled_index`: For each water point, the total number of recorded events within a 10 km buffer of its GPS location for the past 10 years (2010 - 2020) is calculated using the Armed Conflict Location and Event Database (ACLED).
- `bgs_dtw`: Extracted point values for each water point GPS location for depth to groundwater (mbgl) using the British Geological Survey Africa Groundwater Atlas.
- `bgs_prod`: Extracted point values for each water point GPS location for groundwater productivity (l/s) using the British Geological Survey Africa Groundwater Atlas.
- `bgs_recharge	`: Extracted point values for each water point GPS location for recharge, the replenishment of groundwater in aquifers by rainfall, using the British Geological Survey Africa Groundwater Atlas.
- `rwi`: This index is an estimate of relative wealth of the people living in each micro-region relative to others in the same country.
- `pressure`: Percent of maximum capacity being utilized based on assigned_population estimate (pressure = assigned_population/usage_cap)
- `criticality`: Ratio of assigned_population to local_population. Indicator of how many alternative functional points are available to poplation.
- `years_since_report`: The number of years since the report date. Calculated by subtracting the report date from today's date.
- `elevation_in_m`:

#### Train set

In [117]:
train_df = pd.read_pickle("./dataset_elevation.pkl")

In [118]:
train_df = train_df[['status_id', 'age_in_years', 'distance_to_primary',
                                'distance_to_city', 'distance_to_town', 'landcover_code', 'acled_index',
                                'bgs_dtw', 'bgs_prod', 'bgs_recharge', 'rwi', 'pressure', 'criticality',
                                'years_since_report', 'altitude`_in_m']]

In [119]:
train_df = train_df.dropna(how='any')

In [312]:
train_df.head()

,status_id,age_in_years,distance_to_primary,distance_to_city,distance_to_town,landcover_code,acled_index,bgs_dtw,bgs_prod,bgs_recharge,rwi,pressure,criticality,years_since_report,altitude`_in_m
0,Yes,5.303326,36394.986551,17705.931711,18451.607045,30,7.0,7.0,0.5,133.193283,-0.402,0.116667,0.075594,5.303326,1242
1,Yes,-1.692027,20943.627740,23535.854658,10316.401780,10,1.0,0.0,0.5,133.193283,0.286,1.420000,0.473333,-1.692027,1183
2,Yes,0.607815,20943.627740,23535.854658,10316.401780,10,1.0,0.0,0.5,133.193283,0.286,1.420000,0.473333,2.299842,1183
3,Yes,19.332361,29766.833400,17741.321230,11348.029995,10,6.0,0.0,0.5,133.193283,-0.402,0.036000,0.012552,19.332361,1241
4,Yes,4.328631,25127.842889,27541.568335,11631.402849,10,6.0,0.0,0.5,133.193283,0.286,0.383333,0.172673,4.328631,1197

In [121]:
train_df['status_id'].value_counts()

Yes    54646
No     11254
Name: status_id, dtype: int64

#### test set

In [153]:
test_df = pd.read_pickle("./testset_elevation.pkl")

In [154]:
test_df = test_df.rename(columns={'orig_status_id': 'status_id'})

In [155]:
test_df = test_df[['status_id', 'age_in_years', 'distance_to_primary',
                                'distance_to_city', 'distance_to_town', 'landcover_code', 'acled_index',
                                'bgs_dtw', 'bgs_prod', 'bgs_recharge', 'rwi', 'pressure', 'criticality',
                                'years_since_report', 'altitude`_in_m']]

In [156]:
test_df = test_df.dropna(how='any')
test_df = test_df[test_df.status_id != 'Unknown']

In [157]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61030 entries, 268 to 80201
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   status_id            61030 non-null  object
 1   age_in_years         61030 non-null  float64
 2   distance_to_primary  61030 non-null  float64
 3   distance_to_city     61030 non-null  float64
 4   distance_to_town     61030 non-null  float64
 5   landcover_code       61030 non-null  int64
 6   acled_index          61030 non-null  float64
 7   bgs_dtw              61030 non-null  float64
 8   bgs_prod             61030 non-null  float64
 9   bgs_recharge         61030 non-null  float64
 10  rwi                  61030 non-null  float64
 11  pressure             61030 non-null  float64
 12  criticality          61030 non-null  float64
 13  years_since_report   61030 non-null  float64
 14  altitude`_in_m       61030 non-null  int64
dtypes: float64(12), int64(2), object(1)
memory usage: 7.4+ MB

In [158]:
test_df['status_id'].value_counts()

Yes        50012
No         10392
Unknown      626
Name: status_id, dtype: int64

# Prediction model
## random forest classifier

In [128]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [159]:
# Init train data
# X_train = pd.get_dummies(train_df, columns=['water_source_clean','management_clean'])
X_train = train_df
X_train = X_train.drop(columns=['status_id'])

y_train = train_df['status_id']

# Init test data
# X_test = pd.get_dummies(test_df, columns=['water_source_clean','management_clean'])
X_test = test_df
X_test = X_test.drop(columns=['status_id'])
y_test = test_df['status_id']

In [160]:
rf_model = RandomForestClassifier(n_estimators=50, random_state=44)
rf_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50, random_state=44)

In [161]:
y_pred = rf_model.predict(X_test)

In [162]:
accuracy_score(y_test, y_pred)

0.8953301654923808

In [163]:
print(classification_report(y_test, y_pred))

C:\Users\lucas\anaconda3\envs\minor-big-data-design\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\lucas\anaconda3\envs\minor-big-data-design\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

          No       0.87      0.52      0.65     10392
     Unknown       0.00      0.00      0.00       626
         Yes       0.90      0.98      0.94     50012

    accuracy                           0.90     61030
   macro avg       0.59      0.50      0.53     61030
weighted avg       0.88      0.90      0.88     61030

C:\Users\lucas\anaconda3\envs\minor-big-data-design\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [164]:
rf_model.predict_proba(X_test)

array([[0.08, 0.92],
       [0.02, 0.98],
       [0.06, 0.94],
       ...,
       [0.6 , 0.4 ],
       [0.56, 0.44],
       [0.22, 0.78]])

In [165]:
importances = rf_model.feature_importances_
columns = X_train.columns
i = 0

while i < len(columns):
    print(f'the importance of feature {columns[i]} is {round(importances[i] * 100, 2)}%')
    i += 1

the importance of feature age_in_years is 8.89%
the importance of feature distance_to_primary is 8.37%
the importance of feature distance_to_city is 8.72%
the importance of feature distance_to_town is 8.54%
the importance of feature landcover_code is 2.18%
the importance of feature acled_index is 4.56%
the importance of feature bgs_dtw is 1.12%
the importance of feature bgs_prod is 1.67%
the importance of feature bgs_recharge is 5.55%
the importance of feature rwi is 5.56%
the importance of feature pressure is 13.25%
the importance of feature criticality is 14.64%
the importance of feature years_since_report is 8.35%
the importance of feature altitude`_in_m is 8.59%

In [ ]:
y_pred_df = pd.DataFrame(y_pred, columns = ['Predicted_status'])
y_pred_df

In [ ]:
proba = rf_model.predict_proba(X_test)

In [ ]:
proba_df = pd.DataFrame(proba, columns = ['Chance_broken','Chance_working'])

In [ ]:
test_df_proba = test_df.copy()
test_df_proba.reset_index(inplace=True)
test_df_proba[['Chance_broken', 'Chance_working']] = proba_df
test_df_proba['Predicted_status'] = y_pred_df

In [ ]:
test_df_proba[['status_id', 'Predicted_status', 'Chance_broken', 'Chance_working']].sample(10)